#ifndef UTILITY_INTERNAL_VERSION_HPP_
#define UTILITY_INTERNAL_VERSION_HPP_ 1

#ifdef _MSVC_LANG
#define UTILITY_CPPLANG _MSVC_LANG
#else
#define UTILITY_CPPLANG __cplusplus
#endif

#define UTILITY_CPP11 201103L
#define UTILITY_CPP14 201402L
#define UTILITY_CPP17 201703L
#define UTILITY_CPP20 202002L
#define UTILITY_CPP23 202302L

#define UTILITY_HAS_CPP11 (UTILITY_CPPLANG >= UTILITY_CPP11)
#define UTILITY_HAS_CPP14 (UTILITY_CPPLANG >= UTILITY_CPP14)
#define UTILITY_HAS_CPP17 (UTILITY_CPPLANG >= UTILITY_CPP17)
#define UTILITY_HAS_CPP20 (UTILITY_CPPLANG >= UTILITY_CPP20)
#define UTILITY_HAS_CPP23 (UTILITY_CPPLANG >= UTILITY_CPP23)

#endif // UTILITY_INTERNAL_VERSION_HPP_
