#ifndef UTILITYCXX_INTERNAL_VERSION_HPP_
#define UTILITYCXX_INTERNAL_VERSION_HPP_ 1

#ifdef _MSVC_LANG
#define UTILITYCXX_CPPLANG _MSVC_LANG
#else
#define UTILITYCXX_CPPLANG __cplusplus
#endif

#define UTILITYCXX_CPP11 201103L
#define UTILITYCXX_CPP14 201402L
#define UTILITYCXX_CPP17 201703L
#define UTILITYCXX_CPP20 202002L
#define UTILITYCXX_CPP23 202302L

#define UTILITYCXX_HAS_CPP11 (UTILITYCXX_CPPLANG >= UTILITYCXX_CPP11)
#define UTILITYCXX_HAS_CPP14 (UTILITYCXX_CPPLANG >= UTILITYCXX_CPP14)
#define UTILITYCXX_HAS_CPP17 (UTILITYCXX_CPPLANG >= UTILITYCXX_CPP17)
#define UTILITYCXX_HAS_CPP20 (UTILITYCXX_CPPLANG >= UTILITYCXX_CPP20)
#define UTILITYCXX_HAS_CPP23 (UTILITYCXX_CPPLANG >= UTILITYCXX_CPP23)

#endif // UTILITYCXX_INTERNAL_VERSION_HPP_
